### ISSUE TITLE
POCA question

### ISSUE THREAD

**Issue by BeRo1985** [cairdac-rd/script-language-fibo-benchmarks#1]
Are you using register variables and fastfunctions at POCA?

For example:

```
fastfunction fibR(reg n){
  n = +n;
  return (n < 2) ? n : (fibR(n-2) + fibR(n-1));
}
```

**Comment by cairdac-rd** [comment]
Hi,
Yes. This is the script used for the test:
```
fastfunction fibR(reg n){
  n = +n;
  return (n < 2) ? n : (fibR(n-2) + fibR(n-1));
}

var N = 36;
let ta = 0, tb = 0;

ta=DateTime.now();
puts("fibR: ", fibR(N));
tb=DateTime.now();
puts("fibR time: ", Math.round(DateTime.milliseconds(tb-ta)), " milliseconds");
puts("");
```

**Comment by BeRo1985** [comment]
And if you do want to see a really fast x86-32-only JITed (but slightly buggy) script engine in ObjectPascal => http://bero.0ok.de/blog/projects/beroscript/BeRoScript.zip  what I've wrote 2002, where I was 16 or 17.  Just run 

> `BSEngine.exe fib.bs`

**Comment by cairdac-rd** [comment]
Yes!!
`` >BSEngine.exe fib.bs
14930352
Ticks: 0.171 s
``
I was not not able to compile it directly because of widechar as default char in Delphi now.

**Comment by BeRo1985** [comment]
Yes, because i wrote it with Delphi 5 or Delphi 7 at that time.
